### ISSUE TITLE
Unserialize references

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#13]
I am wondering if the default unserializer can handle references?

Currently I am doing:

``` php
$theme = $this->getUnserializer()->fromArray($data, 'Zoop\Legacy\Theme\DataModel\AbstractTheme');
```

My model is (note it's json but I convert to array before putting into unserializer)

``` json
{
    "type": "private",
    "id": "5286edca7f8b9abf141889d3",
    "name": "simple name",
    "writeable": true,
    "deleteable": true,
    "assets": [{
            "type": "folder",
            "id": "5286edca7f8b9abf141889d4",
            "name": "assets",
            "pathname": "assets",
            "path": "",
            "parent": {
                "$ref": "Theme\/5286edca7f8b9abf141889d3"
            },
            "theme": {
                "$ref": "Theme\/5286edca7f8b9abf141889d3"
            },
            "writable": false,
            "deletable": false,
            "createdOn": "2013-11-16T04:00:09+00:00",
            "sortBy": 0
        }]
}
```

The problem seems to be with the `parent` and `theme` references. eg

```
PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Class '' does not exist' in /mnt/www/zoop/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:96
```

But without those 2 references it works. 

Is that a problem with the unserializer? Or should we have the serializer remove this metadata before pushing it out to dojo?

**Comment by joshystuart** [comment]
Btw; I realise using `@Shard\Serializer\Ignore` we can remove the metadata, but I'm just wondering if that is the best thing to do?

**Comment by superdweebie** [comment]
Yes the unserializer should handle references. There are some tests in shard-module that do that (eg: https://github.com/zoopcommerce/shard-module/blob/master/tests/Zoop/ShardModule/Test/Controller/RestfulControllerUpdateTest.php#L99), however I think you've found a bug. There needs to be some test coverage for this in shard itself. I'll be able to do it Monday or before.

By the way, if you want to, you can use `$this->getUnserializer()->fromJson(...)` and shard will do the json to array conversion for you.

**Comment by joshystuart** [comment]
Thanks. For now I've just ignored these references as it seems to work ok without them.

Yeah, I knew there was that function, but because I'm not using zf2 JsonController, I have to do some stuff to get the data from put requests. So it's already formatted as an array, which is why I just pass it through as an array.

**Comment by superdweebie** [comment]
fyi reference unserisalization should follow this path:

When unserializing a field, recognise that it is an association ( ref or embed) and branch here: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Unserializer.php#L146

Check for reference:https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Unserializer.php#L16

Load reference: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Unserializer.php#L171

**Comment by superdweebie** [comment]
Ah, I think I might know the issue. If you are using a discriminator map, then this line will fail: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Unserializer.php#L166

With a discriminator map, there is no single target class. I'll need to update the code to handle abstract classes with a disciminator map.

**Comment by superdweebie** [comment]
With no target class set on the association, it makes sense of the error message you've got - ie can't find class `empty string`.

**Comment by joshystuart** [comment]
That would make sense. Tricky stuff!

**Comment by superdweebie** [comment]
Just fixed with ab2042417c143cbbedc5a6dbe5e3209a7b6e8e2b

**Comment by superdweebie** [comment]
Tagged `3.0.3` you should get the fix with a composer update.

**Comment by joshystuart** [comment]
Thanks!
