### ISSUE TITLE
Serializing Embed Many without DiscriminatorField

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#15]
You can Embed Many without DiscriminatorField like:

``` php
/**
     * @ODM\EmbedMany(
     *  discriminatorMap={
     *     "FixedAmountOff"    = "Zoop\Legacy\Promotion\DataModel\Discount\FixedAmountOff",
     *     "PercentageOff"     = "Zoop\Legacy\Promotion\DataModel\Discount\PercentageOff",
     *     "SetAmount"         = "Zoop\Legacy\Promotion\DataModel\Discount\SetAmount",
     *     "WholesalePrice"    = "Zoop\Legacy\Promotion\DataModel\Discount\WholesalePrice"
     *   }
     * )
     */
    protected $discounts;
```

Which results in:

``` json
  "discounts" : [{
      "value" : "15",
      "_doctrine_class_name" : "PercentageOff"
    }],
```

But using the shard serializer it results in:

``` json
"discounts": [{
    "value": "15",
    "": "PercentageOff"
}],
```

Thoughts?

**Comment by joshystuart** [comment]
http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/embedded-mapping.html

**Comment by superdweebie** [comment]
Yep, you've found another bug in shard. I'll do the fix tomorrow, and push in the evening.

Although, as you point out, shard should support this, I'd suggest that explicitly setting the discriminator field is better, so that the consumer of the json gets a cleaner, nicer looking document. `_document_class_name` is a bit ugly.

**Comment by joshystuart** [comment]
No rush I my end. I actually added discriminator fields on all embeds and that is working nicely.

**Comment by joshystuart** [comment]
Another part of this bug is an EmbedOne does not Serialize the discriminator field
eg.

``` php
/**
     * @ODM\EmbedOne(
     *   discriminatorField="type",
     *   discriminatorMap={
     *     "Order"          = "Zoop\Legacy\Promotion\DataModel\Discount\Variable\Order",
     *     "Products"       = "Zoop\Legacy\Promotion\DataModel\Discount\Variable\Products",
     *     "Shipping"       = "Zoop\Legacy\Promotion\DataModel\Discount\Variable\Shipping"
     *   }
     * )
     */
    protected $variable;
```

Results in:

``` json
"variable": {
    "name": "Order"
},
```

Notice it's missing `type`.

**Comment by joshystuart** [comment]
By the way, the latter EmbedOne bug also effects the Unserializer as well.

eg.

``` json
"variable": {
     "type": "Product",
     "name": "Product"
},
```

Will result in a Class not found error.

**Comment by superdweebie** [comment]
I've fixed the first issue you raised. I'll add a fix for the second (single entity) in the next day and then merge it all.

**Comment by joshystuart** [comment]
Hooray!

Thanks!! I've been working around the bug all morning.

**Comment by superdweebie** [comment]
I'll tag a new release when #17 is resolved.

**Comment by joshystuart** [comment]
I tagged it already, but maybe we can delete it and re-tag when #17 is resolved.

**Comment by superdweebie** [comment]
No prob. I'll just increment the tag after #17
