### ISSUE TITLE
Should "patch" observe empty fields?

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#22]
For example:

The document exists as:

```
{
    name: 'joe blw',
    phone: [
        {
            label: 'home',
            number: '999 999 999'
        },
        {
            label: 'mobile',
            number: '400 000 000'
        }
    ]
}
```

If the unserializer receives:

```
{
    name: 'joe blow',
    phone: []
}
```

Should it remove the phone numbers or ignore it, as it currently does.

I think the former should apply here. 

However, if the field is omitted altogether eg.

```
{
    name: 'joe blow'
}
```

Then I feel it should also be omitted from the patch.

**Comment by superdweebie** [comment]
I agree with you. You're finding lots of bugs. :(

**Comment by joshystuart** [comment]
That's a good thing! It's getting a real world work out now :D

**Comment by joshystuart** [comment]
What are your thoughts on the following:
Original document:

```
{
    name: 'joe blw',
    phone: [
        {
            label: 'home',
            number: '999 999 999'
        },
        {
            label: 'mobile',
            number: '400 000 000'
        }
    ]
}
```

Patch document:

```
{
    name: 'joe blow',
    phone: [
        {
            label: 'home',
            number: '999 999 999'
        }
    ]
}
```

Should the `phone` field be a setter or adder? 

It seems to me that it should "set" not "add" a new phone number, otherwise there's no way to control this in `patch` mode.

**Comment by superdweebie** [comment]
I agree with you, it should be a setter.

In shard-module, if the original document is at a rest endpoint such as `/rest/mydoc` then the phone collection can also be accessed by `/rest/mydoc/phone` for fine grained control if required.

**Comment by joshystuart** [comment]
Ok cool. So you could post/put to the `phone` document if you need to add more.

I'll have a fix through shortly.

**Comment by superdweebie** [comment]
Exactly.

**Comment by joshystuart** [comment]
I'm having some trouble;

I fixed this bug, along with the PHPMD bugs, and ended up with some eager reference bugs that I'm working through now. Might not get this done till the morning.

**Comment by superdweebie** [comment]
No problem - I'm not the one waiting for it!

If you need some help, just sing out.

In terms of order of development, this is what I normally do (of course it isn't always as simple and linear as this):
- Write the test, and run it (making sure it fails).
- Patch the source, not caring a lot about code quality. Just keep hacking till it works.
- Run phpmd and refactor any issues
- Run php-cs-fixer. Then run phpcs and fix any remaining cosmetic things

**Comment by joshystuart** [comment]
As we spoke about https://github.com/crimsonronin/shard/tree/Hotfix/PatchUnserializer

Problems: 
https://github.com/crimsonronin/shard/blob/Hotfix/PatchUnserializer/tests/Zoop/Shard/Test/Serializer/SerializerReferenceTest.php#L90

https://github.com/crimsonronin/shard/blob/Hotfix/PatchUnserializer/lib/Zoop/Shard/Serializer/Unserializer.php#L220

**Comment by superdweebie** [comment]
I've found the problem and have a patch on the way. You're right the problem was with the eager serializer. In particular, the eager serializer didn't work correctly when the maxNestingDepth of the serializer was reached. The weird behaviour with the ingredients collection of a cake was due to circular references.

The patch I'm pushing fixes the bug, but comes with a (small I think) bc break. Basically the RefSimple reference serializer has been removed because using it could cause serialized documents to unreliably unserialize. I think that's a good thing, it actually makes the code simpler.

**Comment by superdweebie** [comment]
Fix merged and tagged. Due to bc break, I've upped version to 3.1, so it will probably require an explicit change in composer.json.

**Comment by joshystuart** [comment]
Wow you were up late with this! Well done finding and fixing it though! 

Thanks heaps!!

**Comment by superdweebie** [comment]
@crimsonronin no problem. It seemed like you really needed it (and it's a little easier to push on when I don't have work the next day).

**Comment by joshystuart** [comment]
:) Really appreciate it.
