### ISSUE TITLE
Unserializer on documents with ID strategy=none

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#30]
Hi @superdweebie ,

Got a pretty rare problem I'd imagine. Basically I have a document like:

`Country.php`

``` php
/**
 * @ODM\Document
 */
class Country
{
    /**
     *
     * @ODM\Id(strategy="none")
     */
    protected $id;

    /**
     * @ODM\String
     */
    protected $name;
}
```

`Address.php`

``` php
/**
 * @ODM\EmbeddedDocument
 */
class Address
{
    /**
     *
     * @ODM\String
     */
    protected $line1;

...

    /**
     *
     * @ODM\ReferenceOne(targetDocument="Zoop\Shard\Test\Serializer\TestAsset\Document\Country", simple="true")
     */
    protected $singleReferencedCountry;
}
```

However the unserializer doesn't work since we look for `$ref`, but in this case the document won't have one.

I've managed to find a way around it using `$metadata->isSingleValuedReference($field)`, but it does mean it is tightly coupled to ODM.

The other problem is, how do we handle `EmbedOne` and `EmbedMany`? There are similar functions eg. `$metadata->isSingleValuedEmbed($filed)` but that causes problems for embedded documents that aren't references.

My repo has the changes as well as the tests both for referenced and embedded documents. Due to the aforementioned problems not all tests will pass.
https://github.com/crimsonronin/shard

Any thoughts?

**Comment by joshystuart** [comment]
I should mention the country id would be the ISO 3166 standard http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by superdweebie** [comment]
Um, I don't think I quite understand. Id strategy=none doesn't mean the document has no id, it just means that it is up to the user to set a unique id, doctrine won't do it for you. To unserialize an address document like above, you should pass something like this:

```
{
    "line1": "blah blah blah",
    "country": {"$ref": "countryId"}
}
```

**Comment by superdweebie** [comment]
I've looked through your branch a bit more, this is probably what you want:

```
Country.php

/**
 * @ODM\Document
 */
class Country
{
    /**
     *
     * @ODM\Id(strategy="none")
     */
     protected $name;
}
```

When unserializing a reference, must always pass it in the format `{"$ref": "id"}`. The presence of the `$ref` is required to give the unserializer the clue it needs that it is a reference. Without it, documents can't be hydrated from the db correctly. The only alternative is including a complete copy of the reference. Eg:

```
{
    "line1": "blah blah blah",
    "country": {"name": "countryId", "otherField": "otherValue" ...}
}
```

**Comment by joshystuart** [comment]
Ah ok. That makes sense!

I was looking at how the document was stored in mongo, and unlike normal references, it didn't have $ref, $collection, $database. 

Thanks

**Comment by superdweebie** [comment]
When you use `simple=true` you get a nice clean simple reference stored in the db. I did experiment in an earlier version of shard allowing the unserialization of simple references like that, but I experienced a few problems. I could go back to it again and I think I could make it work. Do you think I should raise an enhancement issue?

**Comment by joshystuart** [comment]
I guess we can put it on the back burner. No need to stress over it at the moment. Thanks
