### ISSUE TITLE
Unserializer patch

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#32]
We discussed a while back the process of patching a collection. It seems now a collection will be removed even if it isn't passed in eg.

Original:

```
{
    name: 'test',
    tags: [
        'tag 1',
        'tag 2'
    ]
}
```

Patched document:

```
{
    name: 'test update'
}
```

This will result in a document without tags. I thought we only removed the tags field if an empty key was passed eg.

```
{
    name: 'test',
    tags: []
}
```

Thoughts?

**Comment by superdweebie** [comment]
Ga! I thought I was finally on top of this.

**Comment by joshystuart** [comment]
All good. I'll have a crack at it.

**Comment by superdweebie** [comment]
Are you using `superdweebie/shard/Hotfix/Validator`? I think I fixed it up in there. See https://github.com/superdweebie/shard/blob/Hotfix/Validator/lib/Zoop/Shard/Serializer/Unserializer.php#L198

I'll give the `doctrine/mongodb-odm` guys a gentle hassle about my patch so my shard branch can be moved.

**Comment by joshystuart** [comment]
ah no! I'll give that a try now. Thanks

**Comment by joshystuart** [comment]
Yep, all good! Thanks
