### ISSUE TITLE
Need to lock the mongodb-odm version down

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#33]
There's been a significant amount of code committed to the `mongodb-odm` repo since the last tag (~224 commits). This is causing problems with shard eg.

They updated the way the `discriminatorField` works, which caused errors in shard.

I've got a fix ready to push, but I'm thinking we should lock the `mongodb-odm` version to a particular commit. eg

``` json
"doctrine/mongodb-odm": "dev-master#dd838e5856e40592a529a1a2f78c6cc55d7ccb65 as dev-master"
```

Thoughts?

**Comment by joshystuart** [comment]
I ended up doing this because it wasn't a big change.

**Comment by superdweebie** [comment]
I completely agree. Part of me has been waiting for a resolution to this discussion https://github.com/doctrine/mongodb-odm/pull/719
