### ISSUE TITLE
Problem with unserializer now

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#47]
I'm having a problem with the unserializer now.

A simple unserializing process like:

``` php
$updatedOrder = $this->getUnserializer()->fromArray(
            $data,
            'Zoop\Legacy\Order\DataModel\Order',
            $order
);
$this->getDm()->persist($updateOrder);
$this->getDm()->flush();
```

If the document already exists, it doesn't get updated. Even if I remove the `persist` function call, it still doesn't update in the DB.

If the document does exist, it creates perfectly.

I seem to recall we had this issue before?

Thoughts?

**Comment by joshystuart** [comment]
Also, there was a problem with mapping.

I have a model like:

``` php
/**
 * @ODM\Document
 */
class Order
{
    /**
     * @ODM\EmbedOne(targetDocument="Zoop\Legacy\Order\DataModel\Total")
     */
    protected $total;
}
```

However in https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Unserializer.php#L235 it cannot find the reference.

If I add:

``` php
} elseif (isset($mapping['targetDocument'])) {
    $targetClass = $mapping['targetDocument'];
} 
```

It works again.

**Comment by superdweebie** [comment]
I'll be able to take a good look in a couple of hours.

**Comment by joshystuart** [comment]
Awesome thanks.

**Comment by superdweebie** [comment]
I've just written a test for your first problem, and it failed. I'll narrow down the problem.

**Comment by joshystuart** [comment]
Thanks. I swore we had fixed this problem in the past :S

**Comment by superdweebie** [comment]
Ok, I've worked out the problem.  It's not a bug, I ammended my test and it's working now. This is what your code should look like:

```
$updatedOrder = $this->getUnserializer()->fromArray(
        $data,
        'Zoop\Legacy\Order\DataModel\Order'
);
$this->getDm()->persist($updateOrder);
$this->getDm()->flush();
```

If you have `$order` like you did, and an order already exists in the db with the same id that is contained in `$data`, but the `$order` instance you're passing to the unserializer isn't managed by the `dm`, then it won't persist the changes. That's becuase the `dm` sees the order as a new document (it isn't managing it), then sees the id conflict, and so throws it away and keeps the one already in the db.

**Comment by superdweebie** [comment]
I've changed the test code to reflect better usage.

**Comment by joshystuart** [comment]
Ah. So I should just ensure that the `$data` contains the right `id`.

Out of curiosity, why would you pass in a document as the third param?

**Comment by superdweebie** [comment]
Possible reasons:
- If you know `$data` doesn't contain an id - then the id from the document is used.
- If you know that your document instance has been pulled from the dm, which saves extra calls to the dm.
- If it's an embedded document that doesn't have an id field.

It's used by the `shard-module` rest stuff a bit.

**Comment by joshystuart** [comment]
Ah ok.

Thanks for the clarification.

I'm still waiting on composer :|

**Comment by superdweebie** [comment]
With the second problem, that's exactly the same annotation used in the unserializer tests here: https://github.com/zoopcommerce/shard/blob/master/tests/Zoop/Shard/Test/Serializer/TestAsset/Document/User.php#L34, which are passing. I don't think I can help without more info, can you tell me how you are generating the error so I can replicate it.

**Comment by joshystuart** [comment]
Maybe the other issue was systemic and caused this issue too. I'll check as soon as composer is finished.

It's weird that everything seemed to work before having 2 connections. :S

**Comment by joshystuart** [comment]
By the way the `$data` doesn't contain the main `id` in my usage:
https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/module/Commerce/src/Zoop/Legacy/Order/Bridge/OrderBridge.php#L24

What's the best way to use it in this case because we only ever store the `legacyId` in session?

**Comment by joshystuart** [comment]
oh actually! I just saw my mistake!

``` php
//add id
        $id = $order->getId();
        if (!empty($id)) {
            $data['id'] = $id;
        }
```

**Comment by superdweebie** [comment]
Two connections is pretty advanced stuff. There aren't many people doing it, and this is the first time trying it with shard.

**Comment by joshystuart** [comment]
ughhhhh. Now I'm getting failed auth on composer......fuuuuuuuuuuuuuuuu. haha. Cursed.

**Comment by joshystuart** [comment]
I'm going to have to give this another shot in the morning.

Thanks for your help and clarification. I'm hopeful tomorrow will be more successful! :)

**Comment by superdweebie** [comment]
Sleep well. Things always look better in the morning.

**Comment by joshystuart** [comment]
So I still had problems with the unserializer but I really couldn't figure out why. In isolation it worked but in context it continued to fail.

So I ended up ditching the unserialize process and just set the variables directly on the model.
