### ISSUE TITLE
Potential issue with access control and console

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#52]
I haven't had time to look into this further, but there's potentially an issue with running `extension.accesscontrol` and using the `console`.

Here's the error:

```
PHP Catchable fatal error:  Argument 1 passed to Zend\Authentication\Adapter\Http::setRequest() must be an instance of Zend\Http\Request, instance of Zend\Console\Request given, called in /mnt/www/sage/module/Sage/src/Zoop/Sage/Service/AuthenticationServiceFactory.php on line 35 and defined in /mnt/www/sage/vendor/zendframework/zendframework/library/Zend/Authentication/Adapter/Http.php on line 278
```

Since I haven't looked further, I'm just using this post as a way to remember when I have time to check it out.

**Comment by superdweebie** [comment]
From the error it looks like a sage problem, not a shard problem. Here's the line: https://github.com/zoopcommerce/sage/blob/master/module/Sage/src/Zoop/Sage/Service/AuthenticationServiceFactory.php#L35

Basically sage origin checking won't work in console, which makes sense. We need to either add code to sage to handle console, or turn off sage module in console mode.

**Comment by joshystuart** [comment]
Ahhh. Thanks I forgot we had registered an authentication service on
bootstrap.

I can sort that out easy.

Thanks.

From the error it looks like a sage problem, not a shard problem. Here's
the line:
https://github.com/zoopcommerce/sage/blob/master/module/Sage/src/Zoop/Sage/Service/AuthenticationServiceFactory.php#L35

Basically sage origin checking won't work in console, which makes sense. We
need to either add code to sage to handle console, or turn off sage module
in console mode.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/zoopcommerce/shard/issues/52#issuecomment-39299126
.
