### ISSUE TITLE
Best way to set ODM Core options

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#9]
Hi @superdweebie 

What's the best way to set odm core config such as:

``` php
'extension.odmcore' => [
    'defaultDb' => $database,
    'proxyDir' => $this->rootPath . '../../data/proxies',
    'hydratorDir' => $this->rootPath . '../../data/hydrators',
],
```

Should I just create a new `DocumentManagerFactory` and pull in the config as needed?

**Comment by superdweebie** [comment]
@crimsonronin if you are using shard-module, then use the standard way of setting options in doctrine-mongo-odm-module. If you are using shard stand alone, then what you have above is perfect for development. It will use the default DeDocumentManagerFactory.

**Comment by joshystuart** [comment]
I'm using shard stand only for now (ie legacy app, trying to use some of the new good stuff).

For some reason it doesn't seem to pick it up in the config. Even this (which I think is the proper semantics):

``` php
'extension.odmcore' => [
    'default_db' => $database,
    'proxy_dir' => $this->rootPath . '../../data/proxies',
    'hydrator_dir' => $this->rootPath . '../../data/hydrators',
],
```

Until I figure it all out, I created a new `DocumentManagerFactory` with some hard coded values. I'm going to need the factory because I need to be able to inject some username/password configs for Mongo.

**Comment by joshystuart** [comment]
By the way, it's working great with the hard coded vars.

**Comment by superdweebie** [comment]
The factory shipped with shard is only there to try and get people up and running quickly. Any production system will need their own factory (or use the one inside doctrine-mongo-odm-module if using zf2). I'll look into the bug and fix it in a few days.

**Comment by joshystuart** [comment]
Yeah I read that in the docs.

Thanks. Much appreciated!

**Comment by superdweebie** [comment]
Closing. Reopen if needed. :)
